name: qbittorrent-enhanced

on:
  schedule:
    - cron: "30 0 * * 0"
  workflow_dispatch:

jobs:
  qbittorrent-enhanced:
    name: Update qBittorrent Enhanced Edition
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Update code by AU
        shell: pwsh
        working-directory: qbittorrent-enhanced
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module AU
          ./update.ps1
      - name: Get new version
        id: version
        run: |
          $latestRelease = ((Invoke-WebRequest -Uri https://api.github.com/repos/c0re100/qBittorrent-Enhanced-Edition/releases/latest -UseBasicParsing).Content | ConvertFrom-Json)[0].tag_name.split("-")[1]
          "latest=$latestRelease" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "qbittorrent-enhanced: Update to v${{ steps.version.outputs.latest }}"
          branch: cpr/qbittorrent-enhanced/${{ steps.version.outputs.latest }}
          delete-branch: true
          title: "CI: Update qbittorrent-enhanced to v${{ steps.version.outputs.latest }}"
          body: |
            Update report
            - Update qbittorrent-enhanced to v${{ steps.version.outputs.latest }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated
            update version
            qbittorrent-enhanced
