name: update_fastfetch

on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:

jobs:
  fastfetch:
    name: Update fastfetch
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Update code by AU
        shell: pwsh
        working-directory: fastfetch
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module AU
          ./update.ps1
      - name: Get new version
        id: version
        run: |
          $latestRelease = ((Invoke-WebRequest -Uri "https://api.github.com/repos/fastfetch-cli/fastfetch/releases" -UseBasicParsing).Content | ConvertFrom-Json)[0]
          echo "latest=$latestRelease.name" >> "$GITHUB_OUTPUT"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "fastfetch: Update to v${{ steps.version.outputs.latest }}"
          branch: cpr/fastfetch/${{ steps.version.outputs.latest }}
          delete-branch: true
          title: "CI: Update fastfetch to v${{ steps.version.outputs.latest }}"
          body: |
            Update report
            - Update fastfetch to v${{ steps.version.outputs.latest }}"
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated
            update version
            fastfetch
          assignees: LandonLi
          reviewers: LandonLi
